version: '2'
services:
    tournoidevincennes-sonar:
        container_name: tournoidevincennes-sonar
        image: sonarqube:6.1-alpine
        ports:
            - 9000:9000
            - 9092:9092
